config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'admin/auth'

  root to: 'offers#index'

  namespace :admin do
    resources :offers, except: [:show]
  end

  resource :locales, only: [:update]
  resources :offers, only: [:index]
end

app/models/admin.rb
# frozen_string_literal: true

class Admin
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
  validates :advertiser_name, :description, :url, :starts_at, presence: true
  validates :advertiser_name, uniqueness: true

  scope :enabled, -> do
    where(disabled: false)
      .where('starts_at <= :time and (ends_at is null or ends_at >= :time)',
             time: Time.zone.now)
  end

  scope :newest_first, -> { order 'id desc' }
  scope :order_by_premium, -> { order 'premium desc' }
  scope :order_by_remaining_time, -> { order 'ends_at nulls first' }

  # The test instructions state that an offer should be disable if:
  #
  # 3. when current time <= ends at, state = disabled
  #
  # I assumed this was incorrect and the instructions actually meant:
  #
  # when current time >= ends at, state = disabled
  #
  # Because there is no sense in disabling an offer before its end time.
  def enabled?
    return false if manually_disabled?
    started = starts_at <= Time.zone.now
    return started if ends_at.blank?
    started && ends_at >= Time.zone.now
  end

  def manually_disabled?
    attributes['disabled']
  end

  def disabled?
    !enabled?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true
end

app/controllers/admin/offers_controller.rb
# frozen_string_literal: true

class Admin
  class OffersController < ApplicationController
    before_action :authenticate_user!
    before_action :load_offer, only: [:show, :edit, :update]

    def index
      @offers = Offer.newest_first
    end

    def show; end

    def new
      @offer = Offer.new
    end

    def edit; end

    def create
      @offer = Offer.new(offer_params)
      created = @offer.save
      flash[:notice] = t('messages.offer.create_success') if created
      return redirect_to admin_offers_path if created
      flash.now[:error] = t('messages.offer.create_error',
                            errors: @offer.errors.full_messages.join(', '))
      render :new
    end

    def update
      updated = @offer.update_attributes(offer_params)
      flash[:notice] = t('messages.offer.update_success') if updated
      return redirect_to admin_offers_path if updated
      flash.now[:error] = t('messages.offer.update_error',
                            errors: @offer.errors.full_messages.join(', '))
      render :edit
    end

    def destroy
      Offer.find(params[:id]).destroy
      flash[:notice] = t('messages.offer.destroy_success')
    rescue ActiveRecord::RecordNotFound
      flash[:error] = t('messages.offer.destroy_error')
    ensure
      redirect_to admin_offers_path
    end

    private

    def load_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit([:advertiser_name, :url, :description,
                                     :starts_at, :ends_at, :premium, :disabled])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def after_sign_in_path_for(_)
    request.env['omniauth.origin'] || admin_offers_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def set_locale
    I18n.locale = session[:locale] if session[:locale]
  end
end

app/controllers/locales_controller.rb
# frozen_string_literal: true

class LocalesController < ApplicationController
  def update
    session[:locale] = params[:locale]
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/offers_controller.rb
# frozen_string_literal: true

class OffersController < ApplicationController
  def index
    @offers = Offer.enabled.order_by_premium.order_by_remaining_time
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def seconds_to_time(seconds)
    time_parts = [seconds / 3600, seconds / 60 % 60, seconds % 60]
    time_parts.map! { |part| part.to_i.to_s.rjust(2, '0') }
    label_parts = [:h, :m, :s]
    parts = time_parts.zip(label_parts).map(&:join)
    parts.join(':')
  end
end

app/helpers/bootstrap_flash_helper.rb
# frozen_string_literal: true

module BootstrapFlashHelper
  # Gera e retorna os flashs vindos do controller para exibir na tela.
  def bootstrap_flash
    capture do
      flash.each do |type, messages|
        bootstrap_alerts_for_type(bootstrap_flash_type(type), messages)
      end
    end
  end

  def bootstrap_alert(type, title_text, dismissable = true)
    content_tag('div', class: "alert alert-#{type} fade show", role: 'alert') do
      concat bootstrap_close_button('alert') if dismissable
      concat content_tag('strong', title_text) if title_text
      concat(content_tag(:span, capture { yield }))
    end
  end

  def bootstrap_close_button(data_dismiss = 'alert')
    span = content_tag('span', '×', aria: { hidden: true })
    button_tag(span, class: 'close', data: { dismiss: data_dismiss },
               aria: { label: t('messages.close') })
  end

  def bootstrap_alerts_for_type(type, messages)
    return if type.blank?
    Array(messages).each do |msg|
      concat(bootstrap_alert(type, nil) do
        simple_format(msg, {}, wrapper_tag: 'span')
      end)
    end
  end

  def bootstrap_flash_type(type)
    { notice: :success, alert: :warning, error: :danger }[type.to_sym]
  end
end

app/helpers/offers_helper.rb
# frozen_string_literal: true

module OffersHelper
  def offer_status(offer)
    t("messages.offer.enabled_#{offer.enabled?}")
  end

  def toggle_offer_status_button(offer)
    return enable_offer_button(offer) if offer.manually_disabled?
    disable_offer_button(offer)
  end

  def enable_offer_button(offer)
    form_for([:admin, offer], html: { class: 'w-100' }) do |f|
      concat f.hidden_field :disabled, value: false
      concat f.submit t('messages.offer.enable'),
                      class: 'btn btn-success btn-block'
    end
  end

  def disable_offer_button(offer)
    form_for([:admin, offer], html: { class: 'w-100' }) do |f|
      concat f.hidden_field :disabled, value: true
      concat f.submit t('messages.offer.disable'),
                      class: 'btn btn-warning btn-block'
    end
  end

  def offer_time_remaining(offer)
    return unless offer.ends_at
    seconds_to_end = offer.ends_at - Time.zone.now
    return seconds_to_time(seconds_to_end) if seconds_to_end < 2.days
    distance_of_time_in_words_to_now(offer.ends_at)
  end
end

app/helpers/title_helper.rb
# frozen_string_literal: true

module TitleHelper
  def title(title_text, subtitle = nil)
    content_for(:title) { title_text }
    content_tag(:h1, class: 'my-4') do
      concat title_text
      concat content_tag(:small, subtitle, class: 'text-muted') if subtitle
      concat content_tag(:hr, nil, class: 'my-2')
    end
  end
end

app/views/admin/offers/_form.html.erb
<%= form_for [:admin, offer] do |f| %>
  <div class="card">
    <div class="card-header">
      <h4 class="my-0"><%= t('messages.offer.information') %></h4>
    </div>
    <div class="card-body">
      <div class="form-group">
        <%= f.label :advertiser_name %>
        <%= f.text_field :advertiser_name, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', type: :url, required: true %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control noresize', rows: 10,
                        maxlength: 500, required: true %>
        <small class="text-muted">
          <%= t('messages.remaining_characters') %>
          <span id="offerDescriptionCounter"><%= 500 - f.object.description.to_s.size %></span>
        </small>
      </div>

      <div class="form-group">
        <%= f.label :starts_at %>
        <%= f.text_field :starts_at, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :ends_at %>
        <%= f.text_field :ends_at, class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="custom-control custom-checkbox">
          <%= f.check_box(:premium, class: 'custom-control-input') %>
          <%= f.label(:premium, class: 'custom-control-label') %>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <%= link_to t('messages.back'), url_for(:back),
                  class: 'btn btn-secondary' %>
      <%= f.submit t('messages.offer.save'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/offers/_offers.html.erb
<div class="card">
  <div class="card-header"><h4 class="my-0"><%= t('messages.offers') %></h4></div>
  <% if offers.present? %>
    <table class="table table-condensed table-bordered table-hover mb-0">
      <thead>
      <tr>
        <th>ID</th>
        <th><%= Offer.human_attribute_name :advertiser_name %></th>
        <th><%= Offer.human_attribute_name :url %></th>
        <th><%= Offer.human_attribute_name :status %></th>
        <th><%= Offer.human_attribute_name :actions %></th>
      </tr>
      </thead>
      <tbody>
      <% offers.each do |offer| %>
        <tr>
          <td><%= offer.id %></td>
          <td><%= offer.advertiser_name %></td>
          <td><%= offer.url %></td>
          <td><%= offer_status(offer) %></td>
          <td>
            <div class="btn-group d-flex" role="group">
              <%= link_to t('messages.edit'), edit_admin_offer_path(offer), class: 'btn btn-secondary w-100' %>
              <!-- I know this enable/disable button isn't flush with the rest
                   of the btn-group, but I let it slip as the test instructions
                   said the layout/design here wouldn't be evaluated. -->
              <%= toggle_offer_status_button(offer) %>
              <%= link_to t('messages.destroy'), [:admin, offer], method: :delete,
                          class: 'btn btn-danger w-100',
                          data: { confirm: t('messages.confirm') } %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="card-body">
      <div class="alert alert-warning">
        <%= t('messages.offer.empty') %>
        <%= link_to t('messages.offer.create_one'), new_admin_offer_path %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/offers/edit.html.erb
<%= title "#{t('messages.offer.edit')} \"#{@offer.advertiser_name}\"" %>

<%= render partial: 'admin/offers/form', locals: { offer: @offer } %>

app/views/admin/offers/index.html.erb
<%= title "#{Offer.model_name.human}s" %>

<div class="card card-body mb-3">
  <%= link_to t('messages.offer.new_button'), new_admin_offer_path,
              class: 'btn btn-primary' %>
</div>

<%= render partial: 'admin/offers/offers', locals: { offers: @offers } %>

app/views/admin/offers/new.html.erb
<%= title 'Create new Offer' %>

<%= render partial: 'admin/offers/form', locals: { offer: @offer } %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>Lemoney Test - Rodrigo Castro Azevedo - 2018</p>
  <p>
    <%= t 'messages.change_language' %>
    <% if I18n.locale == I18n.default_locale %>
      <%= link_to locales_path(locale: 'en'), method: :patch do %>
        English
        <%= flag_icon(:us) %>
      <% end %>
    <% else %>
      <%= link_to locales_path(locale: 'pt-BR'), method: :patch do %>
        Português
        <%= flag_icon(:br) %>
      <% end %>
    <% end %>
  </p>
  <p class="mb-0"><a href="#"><%= t('messages.back_to_top') %></a></p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Lemoney Test', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to root_path, class: 'nav-link' do %>
          Home
          <span class="sr-only">(current)</span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Lemoney Test', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to root_path, class: 'nav-link' do %>
          <%= t('messages.home') %>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to offers_path, class: 'nav-link' do %>
          <%= t('messages.client_home') %>
        <% end %>
      </li>
    </ul>

    <ul class="navbar-nav navbar-user">
      <li class="nav-item">
        <span class="nav-link"><%= current_user.username %></span>
      </li>
      <li class="nav-item">
        <%= link_to t('messages.sign_out'), destroy_user_session_path,
                    class: 'nav-link nav-signout-link', method: :delete %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar_client.html.erb
<div class="jumbotron jumbotron-header wrapper">
  <h1 class="display-4">
    <%= link_to 'lemoney test', root_path, class: 'link-undecorated' %>
  </h1>
  <p class="lead"><%= t('messages.description') %></p>
  <!-- Btw "non-existing offers" refer to the offer being a fake offer
       created by the seeds.rb file -->
  <%= link_to 'Admin', admin_offers_path, class: 'jumbotron-admin-link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <title><%= content_for?(:title) ? "#{yield(:title)} - Lemoney Test" : 'Lemoney Test' %></title>

  <meta name="description" content="<%= t('messages.description') %>">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <%= csrf_meta_tags %>

  <link href="https://fonts.googleapis.com/css?family=Ubuntu:500" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= controller_path.tr('/', '_') %> <%= action_name %>">
<% if controller.class.parent == Admin %>
  <%= render partial: 'layouts/navbar_admin' %>
<% else %>
  <%= render partial: 'layouts/navbar_client' %>
<% end %>

<div class="container py-3">
  <%= bootstrap_flash %>

  <%= yield %>
</div>

<%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/offers/_offer.html.erb
<div class="card card-offer card-body mb-4 text-center
            <%= offer.premium ? 'border-success' : 'border-info' %>">
  <h5 class="mb-5 mt-3"><%= offer.advertiser_name %></h5>

  <% if offer.premium %>
    <span class="offer-premium-badge">
      <%= Offer.human_attribute_name :premium %>!
    </span>
  <% end %>

  <%= link_to t('messages.shop_now'), offer.url,
              class: "btn btn-lg mx-5 #{offer.premium ? 'btn-success' : 'btn-info'}" %>

  <% if offer.ends_at %>
    <span id="offer_time_counter_<%= offer.id %>"
          class="badge badge-pill text-danger border border-danger mx-5 mt-3"
          data-ends_at="<%= offer.ends_at.localtime.strftime('%Y-%m-%d %H:%M:%S') %>">
      <%= t('messages.ends_in') %>
      <strong><%= offer_time_remaining(offer) %></strong>
    </span>
  <% else %>
  <span class="badge text-white border border-white mt-3" aria-hidden="true">
    &nbsp;
  </span>
  <% end %>
</div>

app/views/offers/_offers.html.erb
<div class="row">
  <% offers.each do |offer| %>
    <div class="col-xs-12 col-md-6 col-lg-4">
      <%= render partial: 'offers/offer', locals: { offer: offer } if offer %>
      <% unless offer %>
        <div class="card card-body card-invisible"></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/offers/index.html.erb
<%= title t('messages.offer.latest') %>

<%= render partial: 'offers/offers', locals: { offers: @offers } %>